# Config file for travis-ci.org

language: php
php:
  - "5.6"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install:
  - composer install
  - sh travis.sh
script: cd _test && phpunit --coverage-clover=coverage.xml --stderr --group plugin_findologicxmlexport

after_success:
    - bash <(curl -s https://codecov.io/bash)