# Config file for travis-ci.org

language: php
php:
  - "5.6"
env:
  - DOKUWIKI=master
  - DOKUWIKI=stable
before_install: wget https://raw.github.com/splitbrain/dokuwiki-travis/master/travis.sh
install:
  - composer install
  - sh travis.sh
script: cd _test && phpunit --stderr --group plugin_findologicxmlexport

before_deploy:
  # Set up git user name and tag this commit
  - composer install
  - git config --local user.name "TheKeymaster"
  - git config --local user.email "d.brader@findologic.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"

deploy:
  provider: releases
  api_key:
    secure: d1f316fd3a236854722181b5992029aa
  file: "demo"
  skip_cleanup: true
  on:
    tags: true

